development:
  adapter: mysql2
  database: htmlParser
  username: htmlParser
  password: Adie8Eik
  host: mysql-server

test:
  adapter: mysql2
  database: htmlParser
  username: htmlParser
  password: Adie8Eik
  host: mysql-server

production:
  adapter: mysql2
  database: htmlParser
  username: htmlParser
  password: Adie8Eik
  host: mysql-server