defaults: &defaults
  adapter: mysql2
  host: localhost
  pool: 10
  encoding: utf8

development:
  <<: *defaults
  database: html_parser_development
  username: root
  password: root

test:
  <<: *defaults
  database: html_parser_test
  username: htmlParser
  password: Adie8Eik

production:
  <<: *defaults
  database: html_parser_production
  username: htmlParser
  password: Adie8Eik

