development:
  adapter: mysql2
  database: groupBuy
  username: groupBuy
  password: blahblah
  host: mysql-server

test:
  adapter: mysql2
  database: groupBuy
  username: groupBuy
  password: blahblah
  host: mysql-server

production:
  adapter: mysql2
  database: groupBuy
  username: groupBuy
  password: blahblah
  host: mysql-server