development:
  adapter: mysql2
  database: html_parser_development
  username: root
  password: root
  host: localhost
  pool: 10
  encoding: utf8

test:
  adapter: mysql2
  database: htmlParser
  username: htmlParser
  password: Adie8Eik
  host: mysql-server
  pool: 10
  encoding: utf8

production:
  adapter: mysql2
  database: htmlParser
  username: htmlParser
  password: Adie8Eik
  host: mysql-server
  pool: 10
  encoding: utf8