crawler:
  cron: "0,15,30,45 * * * *"
  class: CrawlerJob  
  queue: crawler
  args: 
  description: "Deals crawler"  
deal_closer:
  cron: "5 * * * *"
  class: DealCloserJob
  queue: deals
  args: 
  description: Check for sold  
snapshot:
  cron: "0 * * * *"
  class: SnapshotJob
  queue: snapshot
  args:
  description: "Update Snapshots"  
chart:
  cron: "30 * * * *"
  class: ChartJob
  queue: chart
  args: 
  description: "Recalculate charts"
