crawler:
  cron: "35 * * * *"
  class: CrawlerJob  
  queue: crawler
  args: 
  description: "Deals crawler"  
deal_closer:
  cron: "10,40 * * * *"
  class: DealCloserJob
  queue: deals
  args: 
  description: Check for sold  
snapshot:
  cron: "5 * * * *"
  class: SnapshotJob
  queue: snapshot
  args:
  description: "Update Snapshots"  
chart:
  cron: "0,40 * * * *"
  class: ChartJob
  queue: chart
  args: 
  description: "Recalculate charts"
statistics:
  cron: "0 4,10,20 * * *"
  class: StatisticsJob
  queue: statistics
  args: 
  description: "Recalculate statistics"
